name: jazrielle-backend
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - pydantic-settings
  - pytest
  - httpx
  - psutil
  - pip
  - pip:
      - --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
      - llama-cpp-python
      - pycaw
